---
########################
#  TASKS  #  mqtt.yml  #
########################
- name: Copy mosquitto configuration.
  ansible.builtin.template:
    src: templates/mqtt/mosquitto.conf.j2
    dest: "{{ volumes['mqtt_config'] }}/mosquitto.conf"
    force: false
    mode: "0644"
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true

- name: Create Mosquitto container.
  containers.podman.podman_container:
    pod: "{{ pod_name }}"
    name: "{{ pod_name }}-mqtt"
    image: "docker.io/library/eclipse-mosquitto"
    state: created
    restart_policy: "on-failure"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ volumes['mqtt_config'] }}/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "{{ volumes['mqtt_data'] }}:/mosquitto/data"
      - "{{ volumes['mqtt_log'] }}:/mosquitto/log"
